### ISSUE TITLE
Integerizing warning/error messages during run

### ISSUE THREAD

**Issue by theocharides** [RSGInc/populationsim#68]
Completing a populationsim run throws these errors/warnings before then finishing successfully:
ERROR- Integerizer failed for COUNTY_5_MAZ_418156 status INFEASIBLE. Returning smart-rounded original weights. 
WARNING- do_simul_integerizing failed for COUNTY_5 status INFEASIBLE. 

These are returned for many of our MAZ/TAZ/COUNTY geographies. Are these simply a limitation of the algorithms that will have populationsim perform in a less sophisticated way, or could it mean something about our controls etc. for those geographies? A couple of our variables aren't coming out great, so wondering if there is a relationship here. Thanks! @lmz

**Comment by bettinardi** [comment]
We're just noticing this warning at ODOT as well, as we are trying to move the synthetic population to future years.  In my spot checks it does appear to be zones with only one household, with a number of controls, and I'm guessing one household can't meet all the controls.   However, the process fails with the error message below.  Do we think these are related, and are there any thoughts on how to track down the issue with the inputs?

WARNING - Integerizer: 1 zero resid_weights
Traceback (most recent call last):
  File "run_populationsim.py", line 62, in <module>
    pipeline.run(models=steps, resume_after=resume_after)
  File "H:\Tools\ModelingTools\PopulationSim\Anaconda2\envs\popsim\lib\site-packages\activitysim\core\pipeline.py", line 571, in run
    run_model(model)
  File "H:\Tools\ModelingTools\PopulationSim\Anaconda2\envs\popsim\lib\site-packages\activitysim\core\pipeline.py", line 472, in run_model
    orca.run([step_name])
  File "H:\Tools\ModelingTools\PopulationSim\Anaconda2\envs\popsim\lib\site-packages\orca\orca.py", line 1987, in run
    step()
  File "H:\Tools\ModelingTools\PopulationSim\Anaconda2\envs\popsim\lib\site-packages\orca\orca.py", line 792, in __call__
    return self._func(**kwargs)
  File "H:\Tools\ModelingTools\PopulationSim\Anaconda2\envs\popsim\lib\site-packages\populationsim\steps\sub_balancing.py", line 276, in sub_balancing
    crosswalk_df=seed_crosswalk_df
  File "H:\Tools\ModelingTools\PopulationSim\Anaconda2\envs\popsim\lib\site-packages\populationsim\steps\sub_balancing.py", line 179, in balance_and_integerize
    sub_control_zones=sub_control_zones)
  File "H:\Tools\ModelingTools\PopulationSim\Anaconda2\envs\popsim\lib\site-packages\populationsim\multi_integerizer.py", line 590, in multi_integerize
    sub_control_zones=sub_control_zones,
  File "H:\Tools\ModelingTools\PopulationSim\Anaconda2\envs\popsim\lib\site-packages\populationsim\multi_integerizer.py", line 375, in do_simul_integerizing
    combine_results=False)
  File "H:\Tools\ModelingTools\PopulationSim\Anaconda2\envs\popsim\lib\site-packages\populationsim\multi_integerizer.py", line 508, in do_sequential_integerizing
    total_hh_control_col=total_hh_control_col
  File "H:\Tools\ModelingTools\PopulationSim\Anaconda2\envs\popsim\lib\site-packages\populationsim\integerizer.py", line 259, in do_integerizing
    status = integerizer.integerize()
  File "H:\Tools\ModelingTools\PopulationSim\Anaconda2\envs\popsim\lib\site-packages\populationsim\integerizer.py", line 156, in integerize
    assert False
AssertionError
Closing remaining open files:output\pipeline.h5...done
PopulationSim run complete!!
16:42:03.68
Press any key to continue . . .

**Comment by toliwaga** [comment]
This error is driven by an edge case that I was doubtful about but had no test case to drive. I have pushed a new test branch to test this. I think we can probably just pull this to master, but  and I will defer to Ben as how best to roll this out.

**Comment by bettinardi** [comment]
would you like our input folder to test it?
